language: python
sudo: required
dist: trusty
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  # get a working ffmpeg
  - sudo add-apt-repository --yes ppa:mc3man/trusty-media
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg
  # install numpy etc. via miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels pypi
  - conda info -a
  - deps='pip libgfortran cython numpy scipy nose pep8'
  - conda create -q -n test-environment "python=$TRAVIS_PYTHON_VERSION" $deps
  - source activate test-environment
  - pip install codecov
install:
  - pip install -e .
  - pip install coveralls
before_script:
  - pep8 --ignore=E402 madmom tests bin
script:
  - nosetests --with-coverage
  # TODO: add executable programs
after_success:
  - codecov
  - coveralls
