version: 1.0.{build}

environment:
  matrix:
    - PYTHON: C:\Python27
      PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
    - PYTHON: C:\Python27-x64
      PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
    - PYTHON: C:\Python35
      PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35
      PYTHON_ARCH: "32"
    - PYTHON: C:\Python35-x64
      PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35-x64
      PYTHON_ARCH: "64"
    - PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36
      PYTHON_ARCH: "32"
    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36-x64
      PYTHON_ARCH: "64"
    - PYTHON: C:\Python37
      PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37
      PYTHON_ARCH: "32"
    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %MINICONDA%"

install:
  # install Miniconda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels pypi
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% pip cython numpy scipy"
  - activate test-environment
  - pip install nose mido
  # Install ffmpeg
  - ps: Start-FileDownload ('http://ffmpeg.zeranoe.com/builds/win' + $env:PYTHON_ARCH + '/shared/ffmpeg-latest-win' + $env:PYTHON_ARCH + '-shared.zip' ) ffmpeg-shared.zip
  - 7z x ffmpeg-shared.zip > NULL
  - "set PATH=%cd%\\ffmpeg-latest-win%PYTHON_ARCH%-shared\\bin;%PATH%"

build: false

build_script:
  - python setup.py build
  - git submodule update --init --remote

test_script:
  - "set PATH=C:\\projects\\madmom\\bin;%PATH%"
  - "set PYTHONPATH=C:\\projects\\madmom;%PYTHONPATH%"
  - python setup.py pytest
